version: '3.7'

services:

  pizza-app-dev:
    container_name: pizza-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'